language: csharp
solution: ./Celloc.sln
install:
  - nuget restore ./Celloc.sln
  - nuget install NUnit.ConsoleRunner -Version 3.5.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./Celloc.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./Celloc.Tests/bin/Release/Celloc.Tests.dll
